import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LoginPage from './login'
import Navbar from '@/components/navbar'
import ProductCard from '@/components/productmui'
import HomePage from './home';
import Layout from '@/components/layout'
import ProductDetail from '@/components/productDetail'
import CartTable from '@/PAGES/cart'
import PaymentPage from './payment'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Echo Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        {/* <PaymentPage/> */}
        {/* <Navbar/>
        <ProductCard/> */}
        <LoginPage/>
        {/* <HomePage/> */}
      </main>
      {/* <ProductDetail/> */}
      {/* <CartTable/> */}
    </>
  )
}


